### ISSUE TITLE
Link to specific entry tabs like DAG or labels

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1267]
### Desired behaviour

Give end-users ability to link to specific tabs by URL

**Comment by agduncan94** [comment]
This seems a bit more complicated than I had hoped. The problem is that we have ngIf on the tabs, so we don't show them until they are vaild. This means that on page load when we try to set a tab based on query params the tab doesn't currently exist in the HTML. This isn't to say it is not doable, but it requires a larger code change than originally thought.

**Comment by denis-yuen** [comment]
Thanks for the heads-up, we'll do this for a future milestone

**Comment by garyluu** [comment]
Possibly unrelated but...there's more *ngIf on tabs for workflows because Files Tab highlighting was somehow interfering with the DAG Tab...highlighting functions were being called continuously once the DAG tab was viewed (even when going to another tab afterwards)
