### ISSUE TITLE
Tests for imports using "../"

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#1456]
### Desired behaviour

For both CWL/WDL, I need tests that see whether our imports (for refresh) and whether TRS works properly with imports and relative paths that go "below" the primary descriptor

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-354)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-354

**Comment by garyluu** [comment]
FYI, it appears to work in production for both refresh and TRS for secondary descriptors (can't check test parameter files because it's absolute).  strangely enough, it doesn't work with develop webservice and ui2 hotfix branch  

Idea for testing... "/file" import "../file" which imports "../file"
absolute structure:
main descriptor: /dirA/dirB/dirC/file
secondary descriptor: /dirA/dirB/file           
imported from secondary descriptor: /dirA/file

relative structure:
main descriptor: /dirA/dirB/dirC/file
secondary descriptor: ../file           
imported from secondary descriptor: ../../file

**Comment by denis-yuen** [comment]
Might have been broken in the refactor. I think this is a case of, add unit tests to expose issue, then fix them

**Comment by melainalegaspi** [comment]
reopen as needed
