### ISSUE TITLE
My Tools/Workflows responsiveness on smaller pages

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1670]
From Gary

> Not sure if related to this PR but with sidebar opened, if viewing in col-xs size, the workflow/tool component is missing. if viewing in col-sm size, the sidebar is possibly unreadable

I like that on small screens (like phones) the sidebar goes over the tool/workflow, as it makes it feel like a phone app. We should make this more obvious though. Thoughts?

As for on col-sm sizes, we do need to find a solution that looks nicer for the sidebar.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-386)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-386
┆Sprint: Backlog
┆Issue Type: Story

**Comment by garyluu** [comment]
For xs, the issue is that the sidebar is expanded by default (pretty much not a sidebar anymore) and selecting the various tools/workflows appears to have no visible change for the average user.

An option (although messy to implement) is to close the "sidebar" after selecting a tool/workflow but probably only in xs size.

A worse option is to show the tool/workflow underneath the "sidebar"
