### ISSUE TITLE
Clicking Refresh All does not show newly shared workflows

### ISSUE THREAD

**Issue by rjbautis** [dockstore/dockstore#1861]
## Feature Request 
Clicking Refresh All in My Workflows does not show newly updated shared workflows.

The UI should make it clear that only user workflows are refreshed or should refresh shared workflows as well.

1. Go to My Workflows page
2. Have another user share a workflow
3. Click Refresh All button and note if shared workflow appears or not

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-426)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-426

**Comment by agduncan94** [comment]
There are a few quick changes we could make:
1) Tooltip for refresh all should specify that it is not for shared workflows
1) Workflow refresh message should specify specify it is not for shared workflows
1) Workflow refresh success message should specify it is not for shared workflows

Related to this, I think we need a way to easily describe non-shared workflows and shared workflows.
Something better than just saying non-shared.

**Comment by denis-yuen** [comment]
Hmmm, alternatively shared workflows should be updated if you have the appropriate rights (writer and above?).

**Comment by agduncan94** [comment]
If we did that, I think we should specify that it refreshes all workflows you have proper rights to.

**Comment by coverbeck** [comment]
This was written up describing the non-refreshing of the list of shared workflows, not the actual content of the shared workflows themselves. I don't think rights don't come into play in this case.

I hadn't thought about the case about refreshing the content/index itself, although I don't think that's an issue today, since only hosted workflows can be shared.

**Comment by denis-yuen** [comment]
Ok, then I think I misread the thread although I think its a bit misleading/confusing. 

If I understand the problem, the refresh process is irrelevant then. The problem is that the Dockstore UI doesn't show newly shared workflows that were shared while you have the UI open, you need to do a hard *browser* refresh to see them. Is my udnerstanding correct?

**Comment by coverbeck** [comment]
Yes, that is correct, although you don't need to do a hard refresh; you could just leave the page and come back.

I think the average user would expect `Refresh` to do that, because the average user (and me too, since I asked Ryan to log this), does not associate the particular meaning of Refresh that Dockstore has in this area, which is to reread from the source control repos.

That said it's probably not likely to happen often, but we were confused by this behavior when we shared workflows with the API and didn't see the newly shared workflows in the UI after clicking the Refresh button.

**Comment by denis-yuen** [comment]
Ah, I think that confusion is understandable. 

But I think it a fix could then be decoupled from a change to the refresh button. 
For example, a live reload function that looks for newly shared workflows (kind of like how new comments are shown on GitHub without reloading) would be sufficient.

**Comment by denis-yuen** [comment]
re-open for specific issues, but I think we're ok here for now
