### ISSUE TITLE
Automatically update the default version of a workflow to the latest release from GitHub

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1975]
https://github.com/nf-core/nf-co.re/issues/65

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-281)
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-281
┆Sprint: Backlog
┆Issue Type: Story

**Comment by denis-yuen** [comment]
This might require some thought since I could imagine both use-cases:
1) A repo (or rather the people managing it) knows that their latest release is always "recommended"
2) A repo creates new releases automatically (kinda like https://github.com/common-workflow-language/cwltool/releases) 

We could maybe rule out draft and pre-releases to be more intelligent about 2)

**Comment by agduncan94** [comment]
I see this as a checkbox where a workflow either uses the latest release from GitHub or they can manually set it. Perhaps another checkbox to say ignore draft/pre releases.
