### ISSUE TITLE
EPAM WDL Visualizations should be cached in a store

### ISSUE THREAD

**Issue by rjbautis** [dockstore/dockstore#2142]
## Feature Request 

WDL Visualizations should be cached into an Akita entity/store. Currently, they are generated on-the-fly each time the component is selected. To reduce latency, the results should be stored and the component should only generate the results if it does not exist in the store already.

For example, multiple versions of the same workflow should be cached.

Relates to ga4gh/dockstore#1557

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-536)
┆Issue Type: Story
┆Sprint: Seabright Sprint 8 Houseboat
┆Issue Number: DOCK-536

**Comment by coverbeck** [comment]
EPAM visualizer has been commented out due to [its lack of WDL 1.0 support](https://github.com/epam/pipeline-builder/issues/56). See [UI code](https://github.com/dockstore/dockstore-ui2/blob/f3aaa31e32238a5758f4cecbafe45032bcf248b9/src/app/workflow/dag/wdl-viewer/wdl-viewer.component.ts#L16).

Closing this ticket; we can revisit if we add it back.
