### ISSUE TITLE
Parameter --entryname does not work for workflows

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2309]
## Bug Report
found during #1216
### Expected behaviour
 The publish command on CLI should use the optional parameter `--entryname` to specify a new name for the entry specified by the required parameter `--entry`. This should register and publish the a copy of the entry under with a new name.

### Actual behaviour
This feature is currently broken for both hosted and non-hosted workflows, but works for tools. The basic publish and unpublish CLI commands still work, just not with `--entryname`.

At first it seemed like it was only broken for hosted workflows since 'dockstore.org' wasn't considered a valid registry, but attempting with non-hosted workflows also result in errors. Seems like [the code](https://github.com/ga4gh/dockstore/blob/065bf4fc35eeef9ec207aac5fa04dd5c0f32f7a8/dockstore-client/src/main/java/io/dockstore/client/cli/nested/WorkflowClient.java#L630) hasn't been updated for a while and needs reworking. 

### Steps to reproduce the behaviour 
You might need to be an owner of the entry for `--entryname`

for tools (works):
```
dockstore tool publish --entry quay.io/ldcabansay/toolpotato --entryname foopotato
```
for workflows:
```
dockstore workflow publish --entry dockstore.org/geezlooueez/granularPotato --entryname delme
```
note: also try with non-hosted workflow. 

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.6.0-rc.0

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-633)
┆fixVersions: Dockstore 2.X
┆friendlyId: DOCK-633
┆sprint: Sprint 50- Yellowfin Tuna
┆taskType: Bug

**Comment by NatalieEO** [comment]
waiting on CLI release to review

**Comment by coverbeck** [comment]
@denis-yuen @Ldcabansay I'm discussing this with Richard, and I started wondering more generally, what is the value of this option? Why should you only be able to give a new entry name when publishing? I guess the use case is you didn't give an entry name when you created it, but now you want one when you publish?

Assuming we still want the feature, which we probably do, how do we handle the "edge" cases that Walt disovered:

* Doesn't work with hosted workflows
* Doesn't work with dockstore.yml workflows

Proposals: 

1. Don't support either of them, and print a nice error message.
2. Don't support .dockstore.yml workflows (which doesn't make sense at all, because the workflow would not be updateable, unless you subsequently changed the .dockstore.yml). But support for hosted workflows, which means you could create a copy of your workflow (but only on publish).
3. Support them both.

I vote for 1.

**Comment by denis-yuen** [comment]
Vote 1 as well

**Comment by coverbeck** [comment]
> ➤ Richard Hansen commented:
> 
> Do we want mirrored functionality for hosted Tools? Currently, when specifying an entryname the hosted tool is registered, but no source files are copied over. (half the functionality of option 2)

I would say no, just print the error message as well.

**Comment by coverbeck** [comment]
A nice error message pops up:

```
DOCKSTORE_VERSION=1.14.0-SNAPSHOT dockstore --config ~/.dockstore/qaconfig workflow publish --entry dockstore.org/coverbeck/helloworld  --entryname delme
ERROR: Dockstore CLI has deprecated the --entryname parameter and may remove it without warning. Please use --new-entry-name instead.
ERROR: Custom entry names are not supported for HOSTED and DOCKSTORE_YML workflows.
√ ~/git/dockstore/dockstore-cli DOCKSTORE_VERSION=1.14.0-SNAPSHOT dockstore --config ~/.dockstore/qaconfig workflow publish --entry github.com/coverbeck/md5sum-dockstore-yml/foobar  --entryname delme
ERROR: Dockstore CLI has deprecated the --entryname parameter and may remove it without warning. Please use --new-entry-name instead.
ERROR: Custom entry names are not supported for HOSTED and DOCKSTORE_YML workflows.
```
