### ISSUE TITLE
Investigate referer header

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#2466]
## Feature Request 

It would be nice to know how often workflows are used (downloaded), in order to track the most popular ones.

This would probably be very imprecise, but we can figure out and generate some data accordingly.

1. How often the workflow's endpoint is being hit
2. Using User-Agent header, who is hitting it (UI, CLI, other)
3. How often Launch with buttons are clicked for which workflows.
4. Web page views.

This came up at an AnVIL tech meeting.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-721)
┆Issue Type: Story
┆Fix Versions: Open-ended research tasks
┆Sprint: Sprint 31 Flounder
┆Issue Number: DOCK-721

**Comment by kathy-t** [comment]
1) dockstore CLI hits certain endpoints to run a workflow, cwltool hits other ones, terra probably similar to cwltool. need ideas for how to aggregate, can we guess?

**Comment by coverbeck** [comment]
Two random thoughts:

1. Is there a way to feed Google Analytics data into Grafana? We probably don't have it so configured, but we could configure the UI to track which buttons are clicked.
2. You might be able to look at the Referer header to distinguish API calls from Terra et al.

**Comment by kathy-t** [comment]
Grafana doesn't have a Google Analytics plug-in, but there is a work-around to get Google Analytics data to Grafana. According to [this](http://googleanalytics.tografana.com/), Google Analytics data could be moved to a data warehouse, such as Postgres, so that Grafana can pick up the data via the Postgres plugin. 

There is already a [third-party solution](https://www.stitchdata.com/integrations/google-analytics/grafana/) that can move Google Analytics data to Postgres (I believe it's free). More details about how this integration works can be found [here](https://medium.com/@rafael.natali/how-to-integrate-google-analytics-into-grafanas-dashboard-e893d9e2af5a). 

Is this something that we wanna do?

**Comment by denis-yuen** [comment]
In general, it could be useful but the Google Analytics interface is pretty good and I don't want to reinvent the wheel there. 

The Referer header sounds like a good idea to look into

**Comment by coverbeck** [comment]
The GA idea was just a vague brainstorm to get additional data to help you figure out who was calling an endpoint. In hindsight, not sure if it would even help. I agree, I don't think we want to recreate the GA UI.

Also, I created an issue, #3113, that when implemented should help distinguish calls made from our UI.

**Comment by coverbeck** [comment]
Another option might be the Origin header. I don't know the details on the difference between the two; you'll need to investigate.
