### ISSUE TITLE
Use ESLint instead of TSLint

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#2563]
### Desired behaviour
TSLint is going to be deprecated at some point (not yet) and will be replaced with ESLint.  Once that's done, flip Codacy ESLint check back on and disable TSLint.

https://medium.com/palantir/tslint-in-2019-1a144c2317a9

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-782)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-782
┆Sprint: Sprint 63- Nurse Shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Looked for a "TSLint in 2020/2021" article 
https://github.com/palantir/tslint/issues/4904 is amusing

https://github.com/angular/angular-cli/issues/13732
leads to https://github.com/angular-eslint/angular-eslint and
https://dev.to/gsarciotto/migrating-and-configuring-eslint-with-angular-11-3fg1 which has Prettier stuff

Since we're on 10 still though going to propose this be 1.12 unless the upgrade to Angular 11 is clean

**Comment by denis-yuen** [comment]
There's a guide now https://blog.ninja-squad.com/2021/03/31/migrating-from-tslint-to-eslint/

**Comment by garyluu** [comment]
Pretty sure it's just the Google search results.  Right now the library supports Angular 11 (it skipped from Angular 8 to 11).  There's also a workaround (https://github.com/coryrylan/ngx-lite/issues/56).

**Comment by denis-yuen** [comment]
Might also be able to see if its even working properly in the Google search results and remove it if it isn't

**Comment by logicappsource** [comment]
How to solve this ?!
