### ISSUE TITLE
Service new versions not showing up

### ISSUE THREAD

**Issue by cricketsloan** [dockstore/dockstore#2768]
Confirm with Andrew

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-912)
┆Issue Type: Story
┆Sprint: Seabright Sprint 17 Raft
┆Issue Number: DOCK-912
┆Epic: Dockstore  My Services

**Comment by agduncan94** [comment]
Occurring with all services. Roughly a week or more since the issue has started.

Tried making multiple releases for existing and new services on Dockstore staging. The lambda is being called but a 418 error is being returned.
Error updating workflow: 418 - Could not create a version. Please ensure that the dockstore.yml is present.

If I redeliver the GitHub payload, the version is added correctly. If I hard refresh/sync then it is added, but this is different code I think.

Maybe a timing issue? Add a delay to queue.

**Comment by denis-yuen** [comment]
Odd, didn't have this issue. 
For example, https://staging.dockstore.org/services/github.com/denis-yuen/app-support-prototype:4.0?tab=info

This sounds like a transient/timing issue

**Comment by denis-yuen** [comment]
On the other hand, having trouble adding a completely new repo

**Comment by denis-yuen** [comment]
i tried a bunch of scenarios:
1) Adding a new repo one-by-one in the GitHub app
2) Adding a new repo to an organization where I had added it to the whole org including future repos

In both cases I tried adding releases. Didn't encounter the initial issue, but I addressed a couple issues I did find in the linked PR
