### ISSUE TITLE
Tools using amazon ECR use docker provider of previously selected tool to create a link to docker image

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2811]
### Expected behaviour
Amazon ECR tools should properly link to the ECR image (or show the name only if there is no link)
### Actual behaviour
Amazon ECR link uses the previously selected provider URL to create a link.

### Steps to reproduce the behaviour 
1. Go to My Tools
1. Have an Amazon ECR tool and a tool from Quay or DockerHub.
1. Select the other tool
1. Select the amazon ECR tool
1. The docker image link should be incorrect (the link will be for the other tool)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-938)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-938

**Comment by cricketsloan** [comment]
➤ Melaina Legaspi commented:

ping [~accountid:5c47ac5281ec9e450cead350] if you need help reproducing the situation

**Comment by agduncan94** [comment]
This is likely also the case for sbgenomics tools.

**Comment by ByteMap** [comment]
The issue causing the bug was the ability to add an ECR tool that does not follow a certain pattern for the Docker Registry Path (*.dkr.ecr.*.amazonaws.com, where * can be any alphanumeric character, internal underscores, and internal hyphens). 

For example, if the ECR tool was registered with the Docker Registry Path as 'registry.amazon.com' the bug would occur, but if the path followed the naming convention the bug would not occur. 

Right now there is no way to add an ECR tool that does not conform to the standard as the user would be displayed with an error message stating that the Registry Path would have to follow the naming convention.
