### ISSUE TITLE
Improve snapshot/DOI/ORCID export click through dialog

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#2846]
### Desired behaviour
Clicking DOI opens dialog that informs user that a version must first create a snapshot to issue DOI, but never explains what a snapshot means. Clicking ‘Snapshot Version’ automatically snapshots the version and then proceeds to dialog regarding DOIs. Edit to add same deal with ORCID export, which requires a DOI.

* Suggestion: There should be an intermediate dialog pop-up that is pretty much identical to stand-alone snapshot dialog

Also, we should increase emphasis on finality of ‘Snapshot’ and ‘Issue DOI’. Right now its really easy to mindlessly click through the actions.

* Perhaps bolding ‘can no longer be edited and cannot be undone’
* In dialog add links to documentation that detail process
* Could also change button text to ‘Confirm Snapshot Version’ and ‘Confirm [verb] DOI’
* We should also finalize and unify verbage for DOI (issue vs. change vs. request)
* Alternatively add a check-box that must be selected before the button can be clicked (might be too much for snapshot since it's already a tag, but the DOI might be a good idea)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-968)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/secure/attachment/10432/image-20210610-191320.png">image-20210610-191320.png</a>
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-968
┆Sprint: Sprint 62- Mako shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
@david4096 cross off the items that are addressed by #787

**Comment by david4096** [comment]
Not done

- Could also change button text to ‘Confirm Snapshot Version’ and ‘Confirm [verb] DOI’
- Alternatively add a check-box that must be selected before the button can be clicked (might be too much for snapshot since it's already a tag, but the DOI might be a good idea)

Done

- In dialog add links to documentation that detail process
- We should also finalize and unify verbage for DOI (issue vs. change vs. request)
- Perhaps bolding ‘can no longer be edited and cannot be undone’

**Comment by david4096** [comment]
From @agduncan94 

> I'm wondering if it should be either repository + '/' + workflowName or repository depending on if the name is present. Not sure if that takes up too much space in the confirm message.
