### ISSUE TITLE
If you reload a hosted workflow page, file contents are not visible.

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2854]
If you snapshot a hosted workflow version and go to the files tab, it will be empty.

Tested in my-workflows

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-975)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Sprint: Seabright Sprint 19 Tanker
┆Issue Number: DOCK-975

**Comment by coverbeck** [comment]
I thought we had said that snapshotting shouldn't be available for hosted workflows, as hosted workflows already can't be modified.

On the other hand, I just realized, maybe snapshotting a hosted workflow could make it undeletable, so it would serve some purpose.

@david4096, do you remember discussing this? I thought you either wrote it down or created a ticket to not show the snapshot action on hosted workflows, but can't remember for sure.

**Comment by agduncan94** [comment]
Note that selecting another workflow which shows the files in the files tab and then selecting the hosted workflow again will properly show the files.

**Comment by denis-yuen** [comment]
Webservice can save hosted workflows as frozen versions
UI can then issue DOIs

**Comment by coverbeck** [comment]
@agduncan94 I saw this too at one point, but now I can't reproduce it, neither in staging nor on a local build. 

Can you still reproduce?

**Comment by agduncan94** [comment]
Yes I am on staging. I made a new version, snapshotted it, generated a DOI, and then manually refreshed the page. When the page loads and I go to the files tab I see no files.

Changing between versions does not fix anything, I have to select another workflow (hosted or non-hosted) and then again select the initial hosted workflow.

**Comment by coverbeck** [comment]
Thanks! I can now reproduce without snapshotted versions being present as well. It does have to be a hosted workflow for me to reproduce.

**Comment by coverbeck** [comment]
This is not working because of the code [here](https://github.com/dockstore/dockstore-ui2/blob/44ca207f2f5b9a3e5fd4752d0110530d79329299/src/app/myworkflows/my-workflow/my-workflow.component.ts#L130):

```
    this.router.events
      .pipe(
        filter(event => event instanceof NavigationEnd),
        takeUntil(this.ngUnsubscribe)
      )
      .subscribe(event => {
        if (this.groupEntriesObject && this.groupSharedEntriesObject) {
          const foundWorkflow = this.findEntryFromPath(
            this.urlResolverService.getEntryPathFromUrl(),
            this.groupEntriesObject.concat(this.groupSharedEntriesObject)
          );
          this.selectEntry(foundWorkflow);
        }
      });
```

When you type in the url directly or reload, no router events fire (none at all), so then `this.selectEntry` doesn't get invoked, which is what leads to the contents being fetched.

@garyluu Any houghts on the best way to handle this and still preserve the logic for invoking selectEntry as it is now when you get to this page by normal means?

Also, FWIW, I think this bug probably doesn't need to block the release, as it's less severe than initially thought.

**Comment by denis-yuen** [comment]
Seems ok on staging.dockstore.org
