### ISSUE TITLE
Investigate get secondary wdl call no longer running in performance load test

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#2929]
After running the load tester on 1.7.0, noticed secondary wdl call no longer gets called. Need to find out why.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1020)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Sprint: Sprint 20 Umiak
┆Issue Number: DOCK-1020

**Comment by coverbeck** [comment]
1. The `/secondaryWdl` endpoint was removed, so the load-tester should not be calling that endpoint. Will create a PR for it.
2. But instead of getting 404s, the endpoint is never invoked at all because of a change in behavior of the `/workflows/published` endpoint where the descriptorType value in the response is now "WDL" instead of "wdl".

```
curl -s "https://staging.dockstore.org/api/workflows/published?limit=10&sortCol=stars" | jq '.' | grep descriptor
    "descriptorType": "NFL",
    "descriptorType": "NFL",
    "descriptorType": "NFL",
    "descriptorType": "WDL",
    "descriptorType": "NFL",
    "descriptorType": "NFL",
    "descriptorType": "NFL",
    "descriptorType": "NFL",
    "descriptorType": "NFL",
    "descriptorType": "NFL",
```

[This code](https://github.com/dockstore/dockstore-load-tester/blob/2060af6e7db3381ec3ee4ce8d5e9e6efedc9b705/src/test/scala/io/dockstore/WorkflowsPageSearch.scala#L60) is checking for lowercase `wdl`, so the endpoint never gets invoked.

```
  .doIfEquals("${descriptorType}", "wdl") {
      exec(
        Workflow.getSecondaryWdl("${id}", "${version}")
      )
```
I didn't actually try this against 1.6 code, but since the `/secondaryWdl` endpoint used to get invoked, it seems safe to assume the value was previously `wdl`, lowercase.

Since the UI is probably the only consumer of this endpoint, it may not be worth fixing the webservice.
