### ISSUE TITLE
Error displayed in Files tab after registering WDL 1.0 workflow

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#2931]
## Bug Report
I registered a WDL 1.0 workflow and it succeeded, but there is an error message displayed on the Files tab for the WDL file and I cannot Publish the workflow.

### Expected behaviour
Files tab should not display an error and Publish button should be active

### Actual behaviour
Error message "/GATKSVPipelineClinical.wdl: WDL file is malformed or missing, cannot extract metadata" is displayed and Publish button is disabled.

### Steps to reproduce the behaviour 
Fork https://github.com/broadinstitute/gatk-sv-clinical
Register the gatk-sv-clinical workflow with GATKSVPipelineClinical.wdl as the primary descriptor
Go to the Files tab for the workflow
Note the error message

![Screen Shot 2019-09-27 at 4 34 53 PM](https://user-images.githubusercontent.com/3650921/65807753-e6570880-e144-11e9-9306-5e461c24f292.png)

### Environment (Browser or OS and Dockstore version)
Google Chrome is up to date
Version 77.0.3865.90 (Official Build) (64-bit)

https://github.com/dockstore/dockstore/releases/tag/1.7.0
https://github.com/dockstore/dockstore-ui2/releases/tag/2.4.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1022)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Sprint: Seabright Sprint 21 Viking
┆Issue Number: DOCK-1022

**Comment by coverbeck** [comment]
[This line](https://github.com/wshands/gatk-sv-clinical/blob/db89e89508bd562cd36e9c316ac968ab0a136c0e/GATKSVPipelineClinical.wdl#L3) is importing a file that doesn't exist.

**Comment by cwhelan** [comment]
It looks to me like that file exists: 

https://github.com/wshands/gatk-sv-clinical/blob/db89e89508bd562cd36e9c316ac968ab0a136c0e/module00a/Module00a.wdl

Unless there's a rule about naming or subdirectories that I don't understand.

**Comment by coverbeck** [comment]
Aargh, sorry about that. I read the first part of the error message and forgot to read the rest of the line. The message is:

`Failed to import 'module00a/Module00a.wdl' (reason 1 of 8): Failed to import 'Structs.wdl' (reason 1 of 1): null`

Structs.wdl is there, so will investigate further.

**Comment by coverbeck** [comment]
Tried debugging a little. Don't have it exactly narrowed down, but think the problem is because the workflow has several Structs.wdl files in different directories and [this code](https://github.com/dockstore/dockstore/blob/405558834a58c431ddbd9f4437b45f05d3b84d18/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/WDLHandler.java#L297) will end skipping some of them.

**Comment by cwhelan** [comment]
@coverbeck Thanks for looking into this. In case it helps, I created a branch in the original repo that removes any extra copies of files and uses relative imports (ie `../`) to import them. I think this is allowed by the WDL spec (it validates using womtool), although I gather that it's frowned upon.

The branch is `cw_relative_imports` in  https://github.com/broadinstitute/gatk-sv-clinical

I tried pointing Dockstore to this branch but I'm still getting the `/GATKSVPipelineClinical.wdl: There was an error creating a Wom Bundle for the workflow.` message on the Files tab.

We use symlinks for all of these duplicate files in our actual development repository, but when I created this new repo for publication in dockstore I ended up de-referencing them since that's how we usually create an imports archive for cromwell. I don't know if there is a better practice for supporting imports that are depended upon by multiple subworkflows in different subdirectories of the root WDL path.

**Comment by coverbeck** [comment]
@agduncan94 I have the master branch of Walt's fork working on my local web service branch. At least partially. It comes up without validation errors, a lot more files are present. On the other hand, the DAG doesn't work, and the Tools tab doesn't show anything

**Comment by acoffman** [comment]
FWIW, I also attempted to register a WDL 1.0 workflow after the 1.7 release and encountered the same issue.

If its useful in debugging, [this is the WDL file in question](https://github.com/hall-lab/sv-pipeline/blob/master/scripts/Pre_Merge_SV.wdl). It also validates with womtool successfully:

```
~/git/sv-pipeline/scripts as acoffman at 3533-al-00004
λ java -jar ~/womtool-46.1.jar validate Pre_Merge_SV.wdl
Success!
```

**Comment by agduncan94** [comment]
@coverbeck I think this is likely due to absolute path vs relative paths, I can investigate the DAG and Tools tab (they use the same code). I'm thinking they refer to the relative paths and not the absolute paths.

**Comment by coverbeck** [comment]
@acoffman Thanks for the additional test case.

I have both your case and the original workflow working in a local branch, but still working on it.

**Comment by agduncan94** [comment]
I forked the repo and tested on 1.8.0-alpha.1 and the workflow is valid. I'll try making a hotfix and cherry-pick the 'Fix WDL import issues' PR to see if it works that way.

**Comment by denis-yuen** [comment]
review pending solution for migration issue

**Comment by denis-yuen** [comment]
Success on staging.dockstore.org
