### ISSUE TITLE
Root path is now /api/api??

### ISSUE THREAD

**Issue by patmagee** [dockstore/dockstore#3059]
###  Bug Report

I am not entirely sure when thiis happened, however the root path for all of the `TRS` endpoints seems to have migrated from `/api/ga4gh` to `/api/api/ga4gh`. To me this is clearly a typo, but it took a long time to figure why my requests were not working, despite using what thte `swagger` docs said was the right url

For example:

The API I would expect to work throws a `404 Not Found`
```
curl -XPOST https://dockstore.org/api/ga4gh/v2/extended/tools/entry/_search
{"code":404,"message":"HTTP 404 Not Found"}
```

whereas the nested `/api/api` endpoint seems to work

```
curl -XPOST https://dockstore.org/api/api/ga4gh/v2/extended/tools/entry/_search
{"took":3,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":529,"max_score":1.0,"hits":[ .... ] } } }
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1098)
┆Issue Type: Story
┆Issue Number: DOCK-1098

**Comment by denis-yuen** [comment]
Hi,
Sorry, its a bit of an oversight on our part, but its not actually a bug. 
Our proprietary API used to be on port 8443, so https://dockstore.org:8443/metadata/config.json for example. That was a bit odd and lead to issues when certain institutions would block port 8443. 
So the above was mirrored at https://dockstore.org/api/metadata/config.json

Unfortunately, that meant that https://dockstore.org:8443/api/ga4gh/v1/metadata is mirrored at https://dockstore.org/api/api/ga4gh/v1/metadata (note that both still work) as does https://dockstore.org:8443/api/ga4gh/v2/extended/tools/entry/_search

Heads-up, long term one of the final reviews ( https://github.com/ga4gh/tool-registry-service-schemas/issues/71 ) changed the base path for TRS v2, so that will eventually become something like 
https://dockstore.org/api/ga4gh/trs/v2/metadata

See https://github.com/ga4gh/tool-registry-service-schemas/blob/2.0.0/openapi/ga4gh-tool-discovery.yaml#L21
