### ISSUE TITLE
Support for v1.2 dockstore.yml for services

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3237]
v1.1 of the dockstore.yml only supported services. The v1.2 version supports workflows and services, along with things like multiple entries per dockstore.yml, and entry names. Users should be able to add services using the v1.2 format.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1213)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 32 Grouper
┆Issue Number: DOCK-1213

**Comment by agduncan94** [comment]
This should include tests that show how a v1.1 service would be converted into a v1.2 service.

**Comment by NatalieEO** [comment]
Tried reviewing this on dev. It was really difficult getting a service updated on Dockstore. I only got it to happen once, randomly, for a branch. Regardless, the one update that did happen was still labeled as version 1.1, but a was marked invalid with the message that it's missing a primary descriptor. https://dev.dockstore.net/services/github.com/NatalieEO/xenahub:master?tab=files

**Comment by coverbeck** [comment]
@NatalieEO , @Ldcabansay used your 1.1 service as a model to bring a service into Docktore with a .dockstore.yml, and it failed because your service's .dockstore.yml has `subclass: docker-compose`, whereas it should have `type: docker-compose`. When she changed it, it worked. Do you think that's the issue you are running into, or is it something else.

As background, it's `subclass` is in the 1.2 version; but `type` is in the 1.1 version.

**Comment by NatalieEO** [comment]
Was able to add a service using v1.2 on production
API - 1.9.0 dockstore 
UI - 2.6.0
