### ISSUE TITLE
Some authenticated endpoints are not so described in OpenAPI

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3264]
**Describe the bug**
On dev.dockstore.net, the lock icon is missing for [updating elastic search](https://dev.dockstore.net/api/static/swagger-ui/index.html#/extendedGA4GH/toolsIndexGet), and when you try to execute the endpoint, you get a 401 error.

I believe this applies for several endpoints, but did not look closely.

Also, when you try to execute it, it is posting an odd body. It shouldn't be posting any body.

**To Reproduce**
1. Go to https://dev.dockstore.net/api/static/swagger-ui/index.html#/extendedGA4GH/toolsIndexGet
2. Click on Try it Out
3. Click Execute

**Expected behavior**
There should be a lock icon next to the endpoint, and after you authorize, your token should be sent in the request.

**Screenshots**
![Screen Shot 2020-02-25 at 12 47 25 PM](https://user-images.githubusercontent.com/1049340/75286239-07438880-57cd-11ea-9b3f-08b29cbc299a.png)

**Additional context**
 - Webservice version: 1.9.0-alpha-3.SNAPSHOT
 - host location: dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1233)
┆Issue Type: Story
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-1233

**Comment by garyluu** [comment]
More info:

We have two openapi.yamls. One is generated at runtime and has all endpoints (even without annotations).  The other one is during `mvn clean install` which only has the endpoints that have the annotations.  

So the ones that are missing authentication is almost certainly due to missing annotation (as shown by the missing description, summary, etc.).  This issue is mostly tied to the older issue to add openapi annotations to everything.  

I'm just going to add authentication for the extendTRS in this issue.

**Comment by Ldcabansay** [comment]
Verified that extendedTRS now correctly handles authentication as of API - 1.9.0-alpha.6
