### ISSUE TITLE
After registering a workflow, the files tab is empty

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#3287]
**Describe the bug**
If you manually register a Galaxy workflow, then navigate to the files tab, no content is displayed.

If you navigate away to another workflow/page, and come back, then the file contents are displayed.

I'm guessing the Galaxy part is not relevant, but only tried it that way, so mentioning it.

**To Reproduce**
1. Go to My Workflows on dev.dockstore.net
2. Click on +
3. Select Register custom remote workflows, then click Next
4. Enter the following
    * Source Code Provider: GitHub
    * Descriptor type: gxformat2
    * Repository: galaxyproject/training-material
    * Path: /topics/variant-analysis/tutorials/dip/workflows/diploid.ga
    * If you've done this before, a workflow name
5. Click Register Workflow
6. After a *long* time, the dialog goes away and you are viewing the registered workflow
7. Click the Files tab -- no content is displayed
8. Navigate to another workflow, then come back -- Files tab now has a file

**Expected behavior**
Files should immediately be visible after registering

**Screenshots**

**Additional context**
 - UI version: 2.5.1-rc.1-13-gfda51175
 - Webservice version: 1.9.0-alpha.4-SNAPSHOT
 - host location: dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1247)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Sprint 34 Isopods
┆Issue Number: DOCK-1247

**Comment by coverbeck** [comment]
Note: this may only happen when you first go the My Workflows page.

**Comment by garyluu** [comment]
This is likely going to be a pain. Seems the ga4gh-file-store does not have the correct information. For example, If you were on a CWL workflow prior to registration, it would initiate updating GA4GH files store with the CWL files, then it would also initiate updating GA4GH files with the galaxy files. 

Both would reset the store to empty and then both HTTP calls finally finish in a non-deterministic order. And then they would both add the files to the database.  Due to other reasons, the component is able to detect something is wrong with the store and just appears empty.

**Comment by NatalieEO** [comment]
Assuming it's the same problem, but this also happens when you refresh the workflow

**Comment by NatalieEO** [comment]
Files appear after registering or refreshing a galaxy workflow
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.6.0-rc.0-12-ga1884d64
