### ISSUE TITLE
Refresh individual version flaky on manually registered workflows

### ISSUE THREAD

**Issue by Ldcabansay** [dockstore/dockstore#3452]
**Describe the bug**
While reviewing #3301 I found that refreshing individual versions of some manually registered workflows resulted in 500 errors. Sometimes works, sometimes doesn't. Brief investigation didn't yield a discernable pattern. Seems to be equally flaky across branches and tags (made sure that they existed on both github and dockstore). Logs show null pointer exceptions:
```
! at io.dockstore.webservice.helpers.GitHubSourceCodeRepo.setupWorkflowVersions(GitHubSourceCodeRepo.java:378
```

**To Reproduce**
Note: try other workflows and their individual versions if this one works for you.
1. Go to https://dev.dockstore.net/my-workflows/github.com/dockstore/hello_world
2. Click on versions tab
3. Select refresh individual version on one of the versions (master errors for me)

Also try some other workflows and see which successes are successful. 

**Expected behavior**
You should be able to refresh an individual version for branches and tags that exist both on source repo and dockstore.

**Screenshots**
![image](https://user-images.githubusercontent.com/23464754/81107428-09604c80-8ecc-11ea-91ce-9267ac1f2f87.png)

**Additional context**
 - UI version: 2.6.0-rc.0-9-g264e5615
 - Webservice version: 1.9.0-alpha.9-SNAPSHOT
 - host location: dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1352)
┆Issue Type: Story
┆Sprint: Sprint 35 Jellyfish
┆Issue Number: DOCK-1352

**Comment by agduncan94** [comment]
Note to self, saw a NullPointerException in the logs
! at io.dockstore.webservice.helpers.GitHubSourceCodeRepo.setupWorkflowVersions(GitHubSourceCodeRepo.java:378)

**Comment by agduncan94** [comment]
Forking the GitHub repo and then trying this from scratch I cannot get the new workflow to have this error. I believe it is the result of the get ref function returning null. If this is null, then the referenceTriple.getLeft() will throw a null pointer exception. I am not sure why this null is being returned though, since the function only returns null if the reference starts with "refs/pull/...".

Not sure if related, but this repository has a tag named master, along with a branch named master.

**Comment by denis-yuen** [comment]
> Not sure if related, but this repository has a tag named master, along with a branch named master.

That seems pretty weird, the underlying repo at least doesn't have this issue

**Comment by agduncan94** [comment]
Managed to recreate locally, I had to use the exact repo and not a fork of it. It seems like the dockstore/hello_world has some hidden refs (ex. refs/pull/1/head) that do not get transferred to forks. These types of refs were already handled by the code and should be ignored. The fix is simply to ignore these hidden refs, and the error will no longer occur.
