### ISSUE TITLE
Cannot link to Zenodo sandbox account on staging

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#3623]
**Describe the bug**
Cannot link to Zenodo sandbox account
(Not sure if this is an anomaly due to staging or sandbox.zenodo.org instead of zenodo.org)

**To Reproduce**
Make sure you are logged out of sandbox.zenodo.org
Go to Dockstore Accounts page
Click on 'Link Account' for Zenodo Account
On Zenodo login page click 'Login with GitHub'
See Zenodo invalid authorization request page

**Expected behavior**
Should have linked Zenodo account and ended up on Accounts page

**Screenshots**
![Screen Shot 2020-06-29 at 11 13 15 AM](https://user-images.githubusercontent.com/3650921/86040944-bbfaea00-b9f9-11ea-8a45-2b88204de4b3.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser Chrome
 - Version Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context**
 - UI version: UI - 2.6.0-rc.5
 - Webservice version: API - 1.9.0-beta.2
 - host location: staging

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1465)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.9
┆Sprint: Backlog
┆Issue Number: DOCK-1465

**Comment by coverbeck** [comment]
I think this is a Zenodo sandbox bug. If I go ahead and login with ORCID (where I do also get the same error), go back to staging, and try to link my account again, I get the ORCID authorization screen and it works. It seems like the issue is Zenodo linking with GitHub/ORCID.

Does this work in prod today? Especially if you log out of Zenodo first?

**Comment by wshands** [comment]
It works on Prod
