### ISSUE TITLE
Replace ng2-ui-auth

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3641]
**Is your feature request related to a problem? Please describe.**
ng2-ui-auth doesn't support Angular 9 and doesn't seem to be supporting it anytime soon (if ever)

**Describe the solution you'd like**
Replace it with https://github.com/manfredsteyer/angular-oauth2-oidc

**Describe alternatives you've considered**
Waiting for ng2-ui-auth to update

**Additional context**
because of https://github.com/dockstore/dockstore-ui2/pull/1023

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1475)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-1475
┆Sprint: 141 - Narbo
┆Issue Type: Story

**Comment by garyluu** [comment]
Check this before updating to Angular 13. Seems like ng2-ui-auth is still as dead as ever.

**Comment by coverbeck** [comment]
Changing the milestone to 1.16, it's preventing the upgrade to Angular 16. I may figure out a workaround, but even so, we should use the newer library.

**Comment by denis-yuen** [comment]
Some extra info for my understanding 
* https://stackoverflow.com/questions/71741596/how-do-i-implement-social-login-with-github-accounts?noredirect=1&lq=1
* we also found in a separate ticket, we can remove the OAuth app and only use a GitHub app to login, but I guess that doesn't support OIDC either https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/differences-between-github-apps-and-oauth-apps

**Comment by coverbeck** [comment]
It turns out we're not heavily using ng2-ui-auth; I'd misunderstood how we use it. I thought we were using the library to generate the links, but we [generally don't](https://github.com/dockstore/dockstore-ui2/blob/d99a76c63a62bae76520a7ee0e1bca168edc2e21/src/app/loginComponents/accounts/external/links.model.ts#L4) -- google is the exception, which we'll need to figure out.

I think/hope it will be fairly easy to have our custom code.
