### ISSUE TITLE
Add tag unique_tag_names error

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3663]
**Describe the bug**
Saw a bunch of `POST /containers/15608/tags HTTP/1.0" 500 210 "-" "Dockstore-CLI/1.9.0/java" 40` issues with multiple different containers.  It appears to be because `ERROR: duplicate key value violates unique constraint "unique_tag_names"`  Still mostly unclear what happened.

**To Reproduce**
1. Try adding a tag from the CLI and see what happens.

**Expected behavior**
1. If it is legit a duplicate tag, then it should not result in a 500 error, should be 400 telling the user it's a duplicate tag.
2. If it is not a duplicate (uhoh), the tag should've been added

**Additional context**
 - host location: dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1491)
┆Issue Type: Story
┆Sprint: Sprint 40 Octopus
┆Issue Number: DOCK-1491

**Comment by GFJHogue** [comment]
Could only reproduce with tag name `latest` - that's probably a hint. In my trails, using other names showed expected behaviour when adding new or duplicate tags.

**Comment by GFJHogue** [comment]
This is a tricky one. Because I have design sprint and still have low bandwidth to work on this, I'll write my latest notes here.

**Details to reproduce:**
1. Create/Publish Tool manually using `dockstore tool manual_publish`
  a. This calls `registerManual` followed by `refresh` and `publish` from DockerRepoResource https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java#L530
2. Add a tag matching the initial tag (default: `latest`) using `dockstore tool version_tag`
  a. This calls `addTags` from DockerRepoTagResource https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoTagResource.java#L155

**What I believe is going on here is**
1. `registerManual` successfully creates the tool and adds the `latest` tag to `tool.getWorkflowVersions()`
2. `refresh` somewhere internally doesn't like the `latest` tag and removes it from `tool.getWorkflowVersions()`
3. `addTags` when attempting to add a duplicate `latest` tag fails to prevent the duplicate add before the `unique_tag_names` SQL error because it was missing from `tool.getWorkflowVersions()`
