### ISSUE TITLE
Refreshing workflow where default version has been deleted on GitHub throws an error

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3752]
**Describe the bug**
A user tried refreshing a workflow but got the following error.

```
The webservice encountered an error.

[HTTP 500] OK: org.hibernate.exception.ConstraintViolationException: could not execute statement could not execute statement ERROR: update or delete on table “workflowversion” violates foreign key constraint “fk_workflow_default_workflowversion” on table “workflow” Detail: Key is still referenced from table “workflow”.
```

It seems like they had a version set as default, but the version was deleted on GitHub. 

See discussion for more information.
https://discuss.dockstore.org/t/error-on-refreshing-workflow-update-or-delete-on-table-workflowversion-violates-foreign-key-constraint/3825

**To Reproduce**
1. Have a workflow with the default version set
2. Delete the version on GitHub
3. Refresh the workflow on Dockstore, see error.

**Expected behavior**
Should delete the default version and then set another as default as a fallback.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1545)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1545
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Story

**Comment by NatalieEO** [comment]
This has already been fixed

**Comment by NatalieEO** [comment]
Confirmed this is fixed in dev
[Webservice](https://github.com/dockstore/dockstore/commits/38d2dd5) - 38d2dd5

[UI](https://github.com/dockstore/dockstore-ui2/commits/f750256a) - 2.7.3-73-gf750256a

[Compose Setup](https://github.com/dockstore/compose_setup/commits/36c8ddc) - 36c8ddc

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/820f90c) - 1.10-58-g820f90c
