### ISSUE TITLE
Build properties seem incorrect

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3962]
**Describe the bug**

For staging, build properties in `dockstore-deploy.properties` are 
```
UiVersion=2.7-fa4b99a
ComposeSetupVersion=1.10
WebserviceTag=1.10.0
DockstoreLambdaKey=0.1.4-cac4598/upsertGitHubTag/function.zip
StackName=Dockstore-1-10-0
```

but the UI reports 

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.0) - 1.10.0
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7) - 2.7
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.1) - 1.1

in the footer

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1662)
┆Fix Versions: Dockstore 1.10.X
┆Issue Number: DOCK-1662
┆Sprint: Sprint 52- Angel shark
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Compose setup is probably cut-off in a regex somewhere

**Comment by coverbeck** [comment]
Also a problem with dockstore-deploy :(

**Comment by GFJHogue** [comment]
So I think I figured out why this popped up. For the first release of 1.10, both `dockstore-deploy` and `compose_setup` were tagged `1.10` instead of `1.10.0`. Then I'm guessing that somewhere the version value is being interpreted as a decimal number, so the trailing `0` gets stripped off.

https://github.com/dockstore/dockstore-deploy/releases/tag/1.10
https://github.com/dockstore/compose_setup/releases/tag/1.10

**Comment by coverbeck** [comment]
> Then I'm guessing that somewhere the version value is being interpreted as a decimal number, so the trailing `0` gets stripped off.

Yes, pretty sure that's it -- I think I meant to comment on this but forgot to. At any rate, I believe if you put these values in double quotes it would fix it: https://github.com/dockstore/compose_setup/blob/47a7d7fcf8e64e86d33fb09a821ce00a35fc5254/templates/web.yml.template#L185

**Comment by GFJHogue** [comment]
It looks like the answer is in the problem - the fix is still only in `develop` of dockstore-compose, thus the push to staging using `1.10.0` won't show the fix.

Paradoxically, the fix is to make a `1.10.1` hotfix for dockstore-deploy, however since dockstore-deploy is the _only_ remaining `1.10` showing as `1.1`, then the hotfix would still cover up the issue even without my PR, thus making this **unreviewable** until someone accidentally types `1.X` instead of `1.X.Y` again 😆

**Comment by GFJHogue** [comment]
As @Richard-Hansen pointed out, let's wait until 1.20 ;)

**Comment by denis-yuen** [comment]
Sigh and sure ...
 @melainalegaspi not sure how to describe something unreviewable until 1.2.0

**Comment by melainalegaspi** [comment]
Closing bc verification is not easily do-able and the code was reviewed.
