### ISSUE TITLE
In Search, the label for Galaxy workflows should be "Galaxy"

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4106]
**Describe the bug**
The label in Search for Galaxy is "GXFORMAT2". It should be Galaxy.

**To Reproduce**
1. Go to https://dev.dockstore.net/search?descriptorType=gxformat2&entryType=workflows&searchMode=files

**Expected behavior**
It should be `Galaxy`. Or maybe `GALAXY`, but I think like `Galaxy` better.

**Screenshots**
![Screen Shot 2021-03-15 at 1 23 17 PM](https://user-images.githubusercontent.com/1049340/111216733-01fcdb80-8592-11eb-9094-9e68ac6bc7d9.png)

**Additional context**
Happens in prod, staging, and dev, but here's the dev build:

[Webservice](https://github.com/dockstore/dockstore/commits/737a7de) - 737a7de

[UI](https://github.com/dockstore/dockstore-ui2/commits/27bfbed2) - 2.7.3-50-g27bfbed2

[Compose Setup](https://github.com/dockstore/compose_setup/commits/f24bc92) - f24bc92

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/cda0452) - 1.10-36-gcda0452

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1739)
┆Issue Number: DOCK-1739
┆Sprint: Backlog
┆Issue Type: Story

**Comment by garyluu** [comment]
Should also change DescriptorLanguage.java for consistency

**Comment by wendidy** [comment]
@garyluu I could just change the front end for this. Since not a lot of places need to display this label, and many of them have already checked whether `descriptorType === 'gxformat2` and show "Galaxy" accordingly. If I modify the backend to "Galaxy", there's a lot to be changed, I feel like it's not necessary

**Comment by denis-yuen** [comment]
Suggesting that rather than using the inline override, try using https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/entry/extendedDescriptorLanguage.ts#L104 with "(preview)" removed or trimmed off. We have a ticket https://github.com/dockstore/dockstore/issues/4107 which we're hoping to get into 1.11 anyway

**Comment by garyluu** [comment]
> @garyluu I could just change the front end for this. Since not a lot of places need to display this label, and many of them have already checked whether `descriptorType === 'gxformat2` and show "Galaxy" accordingly. If I modify the backend to "Galaxy", there's a lot to be changed, I feel like it's not necessary

Searching for `descriptorType === 'gxformat2` returns 1 place that converts what would've been "Galaxy (preview)" to "Galaxy" + preview badge which is consistent enough.

**Comment by coverbeck** [comment]
Verified it's working in dev.

[Webservice](https://github.com/dockstore/dockstore/commits/580a271) - 580a271

[UI](https://github.com/dockstore/dockstore-ui2/commits/d167ef76) - 2.7.3-72-gd167ef76

[Compose Setup](https://github.com/dockstore/compose_setup/commits/36c8ddc) - 36c8ddc

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/da5d5ab) - 1.10-56-gda5d5ab
