### ISSUE TITLE
Improve new user experience for GitHub Apps based workflow

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#4179]
**Is your feature request related to a problem? Please describe.**
A first-time user followed the instructions to register a workflow on Dockstore with GitHub Apps, did a refresh and got an error with a big red box. While the user should not have done nor needed to do a refresh, it's a bad intro to the product.

**Describe the solution you'd like**
Figure out why the user felt the need to click refresh. Based on that, some or all of the following suggestions may apply: 

* Documentation should steer users the right way
* The refresh button should not be available for .dockstore.yml workflows (it may not be, maybe this is because the first entry didn't come in?)
* A friendlier error message -- no big red box, and/or a message saying to push to GitHub to see your changes, or...

**Additional context**
See this [Slack discussion](https://app.slack.com/archives/C16ET3CF4/p1617917888044600).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1763)
┆Fix Versions: Dockstore 1.12
┆Issue Number: DOCK-1763
┆Sprint: Sprint 74- Aquaman
┆Issue Type: Story

**Comment by DailyDreaming** [comment]
I am le user in question.

Here's the screenshot of the error.

![Screenshot from 2021-04-08 14-33-12](https://user-images.githubusercontent.com/20567496/114249427-6d4a8b00-994f-11eb-9229-1a31d78f8ff4.png)

I felt the need to refresh because I was figuring out the repository and deleted the old one with the `.dockstore.yml` file in it.  This broke the ability to be refreshed and cannot be deleted from dockstore, so I had to recreate it and rename some files.  The renaming did not show up in dockstore, so I attempted to hit refresh.  That was when the error message popped up.  It refreshed on its own after a while (5 minutes?  I don't recall how long exactly).

**Comment by DailyDreaming** [comment]
Probably should be a separate issue but... because of my renaming, I have a lot of "unpublished" repo workflows that cannot be deleted:

![Screenshot from 2021-04-09 16-24-54](https://user-images.githubusercontent.com/20567496/114249741-4b053d00-9950-11eb-804a-8550519f9ba3.png)

Only two of the above actually exist: https://github.com/data-metrics/sha256
