### ISSUE TITLE
Add support for GitHub Container Registry tools

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#4353]
Split out from #4002. This should implement part 2 of #4002: add support for GitHub Container Registry tools either via the existing tools feature or sync up with GitHub Apps but for tools #3476.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1857)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10640">image-20220209-145353.png</a>
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1857
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Story

**Comment by denis-yuen** [comment]
`gathering GHCR image information like checksums.` is probably more important because it would also be applicable to workflows that use GHCR images. 

`GHCR tools will be registered using the “Create tool with descriptors on remote sites” option` a bit less important since we should be slowly discouraging old-style tools based on github apps discussion

**Comment by kathy-t** [comment]
> `gathering GHCR image information like checksums.` is probably more important because it would also be applicable to workflows that use GHCR images.

Workflows currently do gather checksums for GHCR images, implemented here: https://github.com/dockstore/dockstore/pull/4352.

We're just missing gathering checksums for GHCR tools on refresh (like we do for other image registries: https://docs.dockstore.org/en/stable/advanced-topics/checksum-support.html#docker-image-checksum-support).
