### ISSUE TITLE
nextflow workflows in nested directories might not be compatible with github apps

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#4468]
**Describe the bug**
See conversation at https://app.slack.com/archives/C16ET3CF4/p1631796772253600
In brief, it looks like describing multiple nextflow workflows in one repo might not be working. 

For implementor @junjun-zhang may have more info

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.11.5) - 1.11.5

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.8) - 2.8

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.11) - 1.11

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.11.0) - 1.11.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1914)
┆fixVersions: Dockstore 1.12
┆friendlyId: DOCK-1914
┆sprint: SEAB 79- Gary (the snail)
┆taskType: Story

**Comment by junjun-zhang** [comment]
ICGC ARGO's setup is similar as Broad's, one github repo can host multiple workflows, like this: https://dockstore.org/workflows/github.com/broadinstitute/gatk/cnv_germline_case_workflow:4.1.5.0?tab=info
and this: https://dockstore.org/workflows/github.com/broadinstitute/gatk/cnv_germline_cohort_workflow:4.1.6.0?tab=info

Both of them are based on the same github repo: https://github.com/broadinstitute/gatk

Also these WARP workflows https://dockstore.org/organizations/BroadInstitute/collections/WARPpipelines are all from the same repo: https://github.com/broadinstitute/warp

I was hoping to have a `.dockstore.yml` like this: https://github.com/broadinstitute/warp/blob/develop/.dockstore.yml would work for Nextflow workflows as well.

**Comment by garyluu** [comment]
Looks like Nextflow with GitHub Apps and others is working as intended as far as I can tell.

https://github.com/garyluu/demo-qc

Things I had to change:
- https://github.com/garyluu/demo-qc/commit/4bb4125490bac0f16115876c1b74f48cfe8b1cb4 because it's invalid otherwise
- https://github.com/garyluu/demo-qc/commit/f07b630b7e595038bf7fb25719c1fd2169470790 to direct to the main.nf because https://github.com/garyluu/demo-qc root directory where the /nextflow.config is has no main.nf
