### ISSUE TITLE
Don't make new users set up the Dockstore CLI

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4797]
**Is your feature request related to a problem? Please describe.**
I love the Dockstore CLI to bits, but it really is optional for a lot of our users. And yet, when new users register, they are taken through the installation of the Dockstore CLI as if it were required to use our platform.

**Describe the solution you'd like**
Installing the Dockstore CLI should be mentioned, but it should be marked as optional.

**Describe alternatives you've considered**
It can be argued that since we're an open platform, people making accounts are likely to be devs, so having new users install the CLI makes sense. But in practice, we have users who are just managing workflows for their institution. We are also likely to have some users make an account even if they don't strictly need one because they may be used to that being a requirement.

**Additional context**
The prod, staging, and dev environments all tell new users to set up the CLI.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2107)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2107
┆Sprint: 107 - Eridanos
┆Issue Type: Story

**Comment by bethsheets** [comment]
We had other suggestions for simplifying the registration process in general.  Do you think this should be scoped in a separate ticket or should this ticket cover reviewing the entire registration process?

**Comment by aofarrel** [comment]
I think that since they're all related, it will be best to keep it on one ticket for now. 

The suggestion that Julian had was to make the final page a little easier to digest. @juklucas can you specify the details?

**Comment by denis-yuen** [comment]
I think the other compromise I had in mind was to list the kinds of things you could do with the CLI in the quickstart.
It does say at the top of https://qa.dockstore.org/quick-start

> Setup our Dockstore CLI application to start launching workflows from the command line.

![Screenshot from 2023-02-24 14-05-34](https://user-images.githubusercontent.com/1730679/221269254-2a086742-c2ec-4033-8df0-445d47160eed.png)

Maybe there's a way of wording it so that if you're a workflow developer or debugger, you should install the CLI. But if you're just curating or starring workflows, you don't need to.
