### ISSUE TITLE
Response from v2 final links to beta API in URL field

### ISSUE THREAD

**Issue by patmagee** [dockstore/dockstore#4881]
**Describe the bug**

The `TRS` specification requires a `Tool` object to have a `name` attribute, but when retrieving a single `tool` from the API, this attribute is named `toolName` in the response.
 
**To Reproduce**
1. Visit any tool (this one for example: https://dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fabelhj%2Fsv-pipeline%2FPre_Merge_SV_v2_terra)
2. Compare the returned json against the TRS spec

**Expected behavior**
To see a `name` attribute in the top level tool object

**Actual behaviour**
See a `toolName` attribute instead

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2157)
┆Attachments: <a href="https://ucsc-cgl.atlassian.net/rest/api/2/attachment/content/10808">image-20220809-191857.png</a>
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2157
┆sprint: 89
┆taskType: Story

**Comment by denis-yuen** [comment]
I think you're looking for https://dockstore.org/api/ga4gh/trs/v2/tools/%23workflow%2Fgithub.com%2Fabelhj%2Fsv-pipeline%2FPre_Merge_SV_v2_terra  (2.0.0 final) rather than https://dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fabelhj%2Fsv-pipeline%2FPre_Merge_SV_v2_terra (2.0 beta.2 ) 

Or use https://dockstore.org/api/static/swagger-ui/index.html#/GA4GHV20 rather than https://dockstore.org/api/static/swagger-ui/index.html#/GA4GH

This was changed in the standard in https://github.com/ga4gh/tool-registry-service-schemas/pull/92

**Comment by patmagee** [comment]
Thanks @denis-yuen for the clarification. I think where I got confused is the fact that the self `url` in the `tool` json from the url you suggest above has the link to the `/api/api/ga4gh` endpoint, and no the `/api/ga4gh` endpoint.

**Comment by denis-yuen** [comment]
Makes sense, we had an internal bug ticket for this for 1.13
(https://ucsc-cgl.atlassian.net/browse/SEAB-3936 for others)
