### ISSUE TITLE
clarify requirements in dockstore.yaml template

### ISSUE THREAD

**Issue by bethsheets** [dockstore/dockstore#5027]
**Is your feature request related to a problem? Please describe.**

The current dockstore.yaml template may needs to be more clear about requirements: https://docs.dockstore.org/en/stable/assets/templates/workflows/workflows.html

or requirements could be added to tips and tricks: https://docs.dockstore.org/en/stable/assets/templates/template.html#tips-and-tricks

**Describe the solution you'd like**
State:
- primary description path should start '/blahblah/', not a relative path './'
- no spaces are allowed in the name field
- is the workflow file ending required?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2207)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2207
┆sprint: 95- W
┆taskType: Story

**Comment by coverbeck** [comment]
Note: comment about primary descriptor path not starting with a relative path, may not be true (I had told Beth that one after reading the logs incorrectly). Implementor should verify.

**Comment by bethsheets** [comment]
Also, what fields are required vs optional?

**Comment by aofarrel** [comment]
In the interests of being concise, I had compiled much of that information [in the last template](https://docs.dockstore.org/en/stable/assets/templates/workflows/workflows.html#full-template-with-explanation-of-all-available-fields). But, ideally, someone shouldn't need to scroll down to that in order to learn that you can't have spaces in the name field. Going to try tinkering with this...

**Comment by aofarrel** [comment]
Thinking of:

* Adding a section in tips and tricks about the naming requirements (covering no spaces and relative path)
* Adding a list of required arguments at the top of every set (tools, wfs, services) of templates... but...

Originally I resisted saying what is and is not required because I wanted to encourage people to fill out the optional author field(s). I'm of the belief that pushing people into filling these out is important to a healthy ecosystem, because users will always know who to contact if something is broken if every entry has a filled-out authorship field; they don't need to go on a git safari to find email addresses. With that in mind I am a little resistant to spelling out what is and is not required outside of the big template document. Instead, by providing a quasi-minimal template at the top, everything that is required will be filled out plus the technically-not-required-but-very-good-idea authorship.

Thoughts? @denis-yuen @coverbeck @bethsheets

**Comment by denis-yuen** [comment]
Honestly, I think I'd agree that https://docs.dockstore.org/en/stable/assets/templates/workflows/workflows.html#filled-out-example-of-a-single-workflow-without-a-name is pretty minimal already. It would be nice to point out the spaces issue, but I'm pretty blah about discouraging recording authorship as well.

**Comment by bethsheets** [comment]
@aofarrel the confusion from the end user was whether a parameter file is required or not to register.

**Comment by denis-yuen** [comment]
On the other hand, if the parameter file is too hard to make for the author of the workflow, one could argue that it would be even harder for a potential user of the workflow to make it. We don't actually validate the test parameter file either, so one could register a silly or empty parameter file while debugging.

**Comment by aofarrel** [comment]
If I recall correctly, I think some Broad workflows are registered with parameter files that have keys but no values, ie "fill in the blank" as opposed to having sample data.

**Comment by aofarrel** [comment]
What if I included a note saying something like "a parameter file is not strictly required, but highly recommended. You can use [insert name of Dockstore CLI command] to generate a fill-in-the-blank parameter file for your workflow."

nb: not 100% sure our CLI has that feature but I think it does, if not, Cromwell does (although that doesn't help with nexflow workflows, and Cromwell is dropping CWL soon)
