### ISSUE TITLE
Building the doc locally causes unwanted changes

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5128]
**Describe the bug**
If you build the doc locally,  `_attic/glossary_entries_list_dynamic.txt` and `dictionary.rst` end up being modified with system specific information that you don't want to commit.

**To Reproduce**
1. Clone dockstore/dockstore-documentation
2. I use a Python 3 virtual environment: `source ~/.virtualenvs/dockstore-doc/bin/activate` (you'll have to create one like this first if you don't have one)
3. `pip install -r requirements.txt`
4. cd docs
5. make clean html
6. git status, see two files from description changed
7. git diff
```
git diff
diff --git a/docs/_attic/glossary_entries_list_dynamic.txt b/docs/_attic/glossary_entries_list_dynamic.txt
index 163859b..cc10fd9 100644
--- a/docs/_attic/glossary_entries_list_dynamic.txt
+++ b/docs/_attic/glossary_entries_list_dynamic.txt
@@ -1,4 +1,4 @@
-DO NOT EDIT THIS FILE. This file is autogenerated from _attic/glossary_generator.py, update that instead.
+DO NOT EDIT THIS FILE. This file is autogenerated from /Users/charlesoverbeck/git/dockstore/dockstore-documentation/docs/_attic/glossary_generator.py, update that instead.
 .dockstore.yml
 AGC
 Amazon Genomics CLI
diff --git a/docs/dictionary.rst b/docs/dictionary.rst
index a7571a5..93a9379 100644
--- a/docs/dictionary.rst
+++ b/docs/dictionary.rst
@@ -1,4 +1,4 @@
-.. DO NOT EDIT THIS FILE. This file is autogenerated from _attic/glossary_generator.py, update that instead.
+.. DO NOT EDIT THIS FILE. This file is autogenerated from /Users/charlesoverbeck/git/dockstore/dockstore-documentation/docs/_attic/glossary_generator.py, update that instead.
```

**Expected behavior**
A build should not change source files that shouldn't be committed. Ideas:

1. Add them to .gitignore
2. Generate relative paths after `DO NOT EDIT THIS FILE`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2242)
┆fixVersions: Dockstore 1.13.x
┆friendlyId: DOCK-2242
┆sprint: Backlog
┆taskType: Story

**Comment by aofarrel** [comment]
## Short answer
[This PR should fix it. ](https://github.com/dockstore/dockstore-documentation/pull/222)

## Long answer
glossarpy blindly takes in whatever is passed in from whatever calls it, in this case, _attic/glossary_generator.py, in order to print the name of the Python file that is generating the dictionary. glossary_generator.py uses Python built-in `__file__` for this. In theory, `__file__` should be returning a relative directory already. Since it is relative on my machine, but not yours, I think that means either:
a) `__file__` works differently in your venv vs my venv (`__file__` is known to have some weird caveats so this is possible)
b) You're running this in your home directory, so the relative path is essentially an absolute path

It shouldn't matter where the code is being run, it should just work, so I made a PR that will get the basename of `__file__`. This means it won't show _attic in the path anymore, but it should be more robust.

**Comment by aofarrel** [comment]
Weirdly enough [it looks like I anticipated this problem](https://github.com/aofarrel/glossarpy/blob/f39e04393b38a182db3dacca07d7ea62877f9074/README.md#keeping-track-of-source-files) but stuck with `__file__` in glossary_generator.py anyway, probably because I want to keep _attic/ in the path and didn't realize (b) was a possibility.

**Comment by aofarrel** [comment]
Another option would be to hardcode the name of the file. Up to you if you'd prefer that. The only caveat is that if the file that generates gets its name changed, then that hardcoded change will need to be adjusted.
