### ISSUE TITLE
ORCID identifiers can end in 'X'

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#5152]
**Describe the bug**
Per the spec, the last character of an ORCID is a checksum and can be the character 'X' (denoting the value 10):
https://support.orcid.org/hc/en-us/articles/360053289173-Why-does-my-ORCID-iD-have-an-X-
https://orcid.org/0000-0002-9079-593X
Currently, the webservice assumes that ORCIDs are four groups of four decimal digits, separated by dashes:
https://github.com/dockstore/dockstore/blob/273cd85d5df19491b298111ed36a5e3b15c522ab/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ORCIDHelper.java#L71
I believe the upshot is that we're not processing about 1 out of 11 valid ORCIDs here:
https://github.com/dockstore/dockstore/blob/273cd85d5df19491b298111ed36a5e3b15c522ab/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java#L816

**To Reproduce**
Investigator should confirm the above behavior.

**Expected behavior**
Valid ORCIDs should be accepted/processed.

**Additional context**
current webservice

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2256)
┆fixVersions: Dockstore 1.13.x
┆friendlyId: DOCK-2256
┆sprint: 97- Yazoo Darter
┆taskType: Story

**Comment by denis-yuen** [comment]
👍

**Comment by coverbeck** [comment]
I am not able to see an ORCID author on staging, nor on my local development build, X or no X. In debugging it, the logic for this PR looks good -- an ORCID id with an ending X passes the regex test and at least locally gets added to the DB, but it's not coming back in the API nor (of course) visible in the UI.

So I could mark this closed, since I think the base issue is addressed, but ideally I should actually be able to see in the UI, can cannot.

Note that I can see a "regular" author.

Using this repo/branch to test: https://github.com/coverbeck/md5sum-dockstore-yml/tree/orcidtest

**Comment by coverbeck** [comment]
I verified that an ORCID id with a trailing X does get put in the database in staging. There is a generic problem that we have been looking at with staging not being able to read public records, and hence not display them on the workflow version table.

I think this is basically done, but to be paranoid, I'm going to wait until this is deployed to prod and verify there.
