### ISSUE TITLE
Implement language version parsing for Nextflow

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5268]
**Is your feature request related to a problem? Please describe.**
View the description of https://github.com/dockstore/dockstore/issues/4320

**Describe the solution you'd like**
Parse Nextflow files for the language version and set it for Nextflow `SourceFile`'s and Nextflow entry `Version`'s. We should update [our Nextflow version](https://github.com/dockstore/dockstore/blob/86ba4b876c0018cd7aff7a43557869473759536d/dockstore-common/src/main/java/io/dockstore/common/NextflowUtilities.java#L44) to one that is at least `22.03.0-edge` because according to their [docs](https://www.nextflow.io/docs/latest/dsl2.html):
> As of version 22.03.0-edge Nextflow defaults to DSL 2 if no version is specified explicitly

> As of version 22.03.0-edge the DSL version specification (either 1 or 2) can also be specified in the Nextflow configuration file

 It will make parsing the Nextflow file easier because we can make assumptions about the default version and we can parse the Nextflow config file.

**Describe alternatives you've considered**
n/a

**Additional context**
Follow up work for https://github.com/dockstore/dockstore/issues/4320

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2294)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2294
┆Sprint: 103 - Arroyo Seco
┆Issue Type: Story

**Comment by coverbeck** [comment]
There doesn't always appear to be a definitive way to know if a Nextflow file is DSL1 or DSL2: https://www.nextflow.io/docs/latest/dsl2.html

1. The pipeline script, e.g., main.nf, **could** have a DSL directive; if it does, it's definitive.
2. The nextflow.config **could** have a DSL directive, in which case it's definitive, but override-able by step 1
3. Otherwise, the DSL default version is determined by the engine version. 22.0.3-edge and newer the default is DSL 2, otherwise it's DSL 1.
4. There are also command-line/environment settings that I think override item 2.

See also https://help.tower.nf/22.1/faqs/#configuration

**Comment by denis-yuen** [comment]
:cry:
