### ISSUE TITLE
Cytoscape error parsing Galaxy workflow

### ISSUE THREAD

**Issue by david4096** [dockstore/dockstore#5285]
**Describe the bug**

A galaxy based workflow returned a 500 error.

```
127.0.0.1 - - [14/Dec/2022:17:06:41 +0000] "GET /workflows/20406/tools/173939 HTTP/1.0" 500 110 "https://dockstore.org/my-workflows/github.com/Delphine-L/iwc/Long_read_assembly_with_Hifiasm_and_HiC_data" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 37
```

The stacktrace appeared as

```
! java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')

<input class="awsui-checkbox-native-input" type="checkbox" override-focus="" id="awsui-checkbox-841" aria-labelledby="awsui-checkbox-841-label awsui-table-0-selection-group awsui-table-0-selection-627">

  | 2022-12-14T09:00:24.227-08:00 | ! at org.galaxyproject.gxformat2.Cytoscape.getElements(Cytoscape.java:118)
-- | -- | --
 


```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.1) - 1.13.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.1) - 2.10.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.1) - 1.13.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.13.2) - 1.13.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2302)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2302
┆Sprint: 103 - Arroyo Seco
┆Issue Type: Story

**Comment by denis-yuen** [comment]
Demonstrated issue in linked test

**Comment by coverbeck** [comment]
This is fixed in qa, although I did see another 500, for a nearby endpoint, but I will log that one separately.

[Domain] - https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/commits/f96e92a) - f96e92a

[UI](https://github.com/dockstore/dockstore-ui2/commits/6cbb12f7) - 2.10.1-95-g6cbb12f7

[Compose Setup](https://github.com/dockstore/compose_setup/commits/e3b0aa3) - e3b0aa3

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/2fd0b7e) - 1.13.2-30-g2fd0b7e

cwlParsingLambdaVersion: n/a

wdlParsingLambdaVersion: n/a

nextflowParsingLambdaVersion: n/a

galaxyParsingLambdaVersion: 0.0.6

checkUrlLambdaVersion: n/a
