### ISSUE TITLE
Source code link for stub workflows contain "null" and doesn't work

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5501]
**Describe the bug**
On staging and QA, the source code link for stub workflows contain a null value and clicking it leads to a 404 on GitHub
![image](https://user-images.githubusercontent.com/25287123/236890394-9d2b6451-0038-43b4-8664-d06ba4e85a3c.png)

**To Reproduce**
1. Go to My Workflows and quick register a workflow to create a stub workflow
2. See that the Source Code link contains null and clicking it leads to a 404

**Expected behavior**
On prod, the source code link for a stub workflow is just a link to the repository. In the case of a stub workflow which has no descriptor file defined (yet), we should also link to the repository instead of to the primary descriptor file.

**Screenshots**
See above

**Additional context**
[Domain] - https://staging.dockstore.org and https://qa.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.11.0-beta.0) - 2.11.0-beta.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.14.0-beta.0) - 1.14.0-beta.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2395)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2395
┆Sprint: 113 - Liao
┆Issue Type: Story

**Comment by coverbeck** [comment]
There's a case where this still happens:

1. In My Workflows, go to a non-stub workflow
2. Then navigate to a stub workflow and see the null.

It looks like it's because we're using the same component instance for both workflows, but the `ngOnChanges()` is assuming that sourceCodeFile and other fields are in their initial state. See [here](https://github.com/dockstore/dockstore-ui2/blob/c2acfce41312b85ec563f9067bd9c0b1327cfbe2/src/app/workflow/info-tab/info-tab.component.ts#L113) -- looks like there are other fields that are also wrong.
