### ISSUE TITLE
Should we include dev dependencies in our 3rd party license file?

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5549]
**Is your feature request related to a problem? Please describe.**
From discussion [here](https://github.com/dockstore/dockstore-ui2/pull/1796/files#r1229881218) -- do we need to have dev dependencies in our license file? We're not distributing those dependencies, so you could argue we don't need to, but we should get legal confirmation.

**Describe the solution you'd like**
If dev dependencies aren't required, remove them from the 3rd party licenses file. This ticket was spun up from a UI PR comment, but is applicable to the backend as well, e.g., we might not need to have `test` scope dependencies in the licenses file.

**Describe alternatives you've considered**
Just be safe and list dev dependencies' licenses too.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2413)
┆Fix Versions: Dockstore 1.15
┆Issue Number: DOCK-2413
┆Sprint: 116 - Ob
┆Issue Type: Story

**Comment by denis-yuen** [comment]
alternative: maybe one file for what we distribute, one for what we use locally

**Comment by david4096** [comment]
I [opened a PR](https://github.com/dockstore/dockstore-ui2/pull/1807) that removes the dev dependencies from the licenses CSV. For the purposes of compliance, we need to abide by the underlying licenses for each and be able to produce them during an audit. For development dependencies, since we don't include the code of those development dependencies I believe that it's not necessary to provide. We have license checker that can be used to review the licenses should the need arise in a future audit.
