### ISSUE TITLE
Not found page should show url you attempted to go to

### ISSUE THREAD

**Issue by coverbeck** [dockstore/dockstore#5728]
**Is your feature request related to a problem? Please describe.**
If you go to some non-existent pages on Dockstore, you are redirected to page-not-found, without any indicator of the url you attempted to navigate to. It makes it had to figure out what you messed up in the url, e.g., you were off by one character.

Sometimes we keep the url, sometimes we redirect to `page-not-found`.

Examples:

1. Go to https://qa.dockstore.org/asdf -> The url in the address bar continues to be https://qa.dockstore.org/asdf, but the page content says Page not found. This is the right way to handle it, IMHO.
1. Go to https://qa.dockstore.org/workflows/asdf -> The url in the address bar changes to https://qa.dockstore.org/page-not-found, and the content is Page not found. You can't tell what url you specified that's causing problems.

**Describe the solution you'd like**

1. Either keep the original, bad URL in the address bar and the contents should be page not found, or
1. Add the original, bad URL to the page content

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2484)
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2484
┆Sprint: 132 - Elutherios
┆Issue Type: Story

**Comment by ll5zh** [comment]
Other possibly related instances:

1 - Site redirects to `page-not-found` (https://qa.dockstore.org/page-not-found) instead of keeping original URL

- https://qa.dockstore.org/users/asdf
- https://qa.dockstore.org/organizations/asdf
- https://qa.dockstore.org/organizations/iwc/collections/asdf
- https://qa.dockstore.org/containers/asdf
- https://qa.dockstore.org/search-containers/asdf
- https://qa.dockstore.org/tools/asdf
- https://qa.dockstore.org/workflows/asdf, but the title displayed in the tab is 'Dockstore | Workflow' instead of 'Dockstore | 404 Page Not Found' like the examples above

2 - Some nonexistent pages redirect to strange URL paths

- https://qa.dockstore.org/search-workflows/asdf becomes https://qa.dockstore.org/https://qa.dockstore.org/search-workflows/asdf
- https://qa.dockstore.org/notebooks/asdf becomes https://qa.dockstore.org/https://qa.dockstore.org/notebooks/asdf
- https://qa.dockstore.org/services/asdf becomes https://qa.dockstore.org/https://qa.dockstore.org/services/asdf
- https://qa.dockstore.org/apptools/asdf becomes https://qa.dockstore.org/https://qa.dockstore.org/apptools/asdf

(It also seems specific entries can't be accessed through URLs of form `search-containers/*` or `search-workflows/*`, as clicking entries from https://qa.dockstore.org/search-containers redirect to `containers/*`, and clicking entries from https://qa.dockstore.org/search-workflows redirect to `workflows/*`)
