### ISSUE TITLE
400/500 error when requesting a DOI for a notebook that already has a DOI

### ISSUE THREAD

**Issue by kathy-t** [dockstore/dockstore#5792]
**Describe the bug**
For a notebook that has no DOIs, requesting a DOI for version 1 succeeds. Requesting a DOI for version 2 fails with a 500 error:

![image](https://github.com/dockstore/dockstore/assets/25287123/6eed64ef-06d2-47ca-a13e-b83fc714ec40)

Requesting a DOI again for version 2 results in a 400 error:

![image](https://github.com/dockstore/dockstore/assets/25287123/5fbf7359-f9e7-47f6-a72a-fb2becd8e86c)

@denis-yuen also reproduced this error for workflows.

**To Reproduce**

1. Go to a notebook or workflow with no DOIs.
1. Request a DOI for one version. It should succeed.
1. Request a DOI for another version. It should fail.

**Expected behavior**
You should be able to request a DOI for a second version.

**Additional context**
[Domain] - https://staging.dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.15.0-rc.1)

* 1.15.0-rc.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.12.0-rc.1)

* 2.12.0-rc.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.15.0-rc.1)

* 1.15.0-rc.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2503)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11129">image-20240214-224157.png</a>
┆Fix Versions: Dockstore 1.16
┆Issue Number: DOCK-2503
┆Sprint: 130 - Carthago
┆Issue Type: Story

**Comment by denis-yuen** [comment]
FYI, I think the patches may be a slightly different but error.
Basically, I think if the zenodo follow-up deposit dies halfway, you're left with a half filled deposit which needs to be cleaned out as the error above indicates. 
My patch ensures that the deposit doesn't die halfway, specifically for the api change reason

**Comment by denis-yuen** [comment]
Confirmed, I was able to reproduce the error. Basically, if we fail creating a new version of a DOI (i.e. a new version under an existing concept DOI), the zenodo site will keep that draft around resulting in the error above. 

The workaround is to login to Zenodo and "discard" the draft and then attempt to export a new DOI. 

Recommending delaying this till later since deleting a pre-existing draft is probably not straight forward and the above patch should deal with the common situation where this occurs
