### ISSUE TITLE
Dockstore not updating workflows since 1.15 release 

### ISSUE THREAD

**Issue by cimendes** [dockstore/dockstore#5806]
**Describe the bug**
Hello! I've noticed that our workflows hosted in dockstore have not been updated to the latest commit since the 8th of February, when v1.15 was released. 

Example: https://dockstore.org/workflows/github.com/theiagen/public_health_bioinformatics/TheiaCoV_Illumina_PE_PHB:v1.0.0?tab=versions

Additionally, no new dev branches have been propagated to dockstore.

Our dockstore.yml file can be found here: https://github.com/theiagen/public_health_bioinformatics/blob/main/.dockstore.yml

Did any update break compatibility with our yml file? 
We just noticed this behaviour today, which we find a bit odd since this release is about a week old now. For example our main branch has had commits on the 12th of February, but that is not reflected on the webpage (https://github.com/theiagen/public_health_bioinformatics/commits/main/workflows) 

Could you please provide us with some assistance regarding this issue? Thank you!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2511)
┆Issue Number: DOCK-2511
┆Sprint: Backlog
┆Issue Type: Story

**Comment by kathy-t** [comment]
Hi @cimendes, thanks for reaching out. Yes, there was an update that broke compatibility with your .dockstore.yml file. 

Prior to our 1.15 release, relative paths were being inconsistently and unreliably processed in various parts of our system.
Therefore, in this release, we have more explicitly deprecated the use of relative file paths in our .dockstore.yml so all workflows with relative paths are now deemed as invalid. 

Your GitHub App logs show that your [test parameter file path uses a relative path](https://github.com/theiagen/public_health_bioinformatics/blob/cb1251f31e101b3da6b748bdeb462b40499c126e/.dockstore.yml#L7), `empty.json`, which is now considered invalid and is the reason why your workflows have not been updated since the 1.15 release on February 8th.

I have created a PR in the https://github.com/theiagen/public_health_bioinformatics repository that changes the relative file paths to absolute paths in the .dockstore.yml file. Please take a look at the PR https://github.com/theiagen/public_health_bioinformatics/pull/346 and merge it so that your workflows are considered valid again and can be updated by Dockstore.

Thanks!
Kathy

**Comment by cimendes** [comment]
Thank you so much @kathy-t ! :) We were thinking that the issue was along the lines of what you've so kindly explained here! I'll be closing this issue as soon as we've confirmed the changes worked as expected!

**Comment by cimendes** [comment]
Closing this issue as proposed changes have resolved the problem. Thank you very much!
