### ISSUE TITLE
The search functionality parses only the source file contents and not the workflow name

### ISSUE THREAD

**Issue by cimendes** [dockstore/dockstore#5817]
**Describe the bug**
Since the latest release (v.1.15.0) the search functionality appears to be broken. Instead of parsing the workflow name it appears to return the closest hit by the content in the source file. This makes searching for workflows very difficult on Dockstore. 

**To Reproduce**

1. Go to https://dockstore.org/search
1. Search any workflow name such as "TheiaProk"
1. See error

**Expected behavior**
The first hit should be the workflow with the closest name

**Screenshots**
![image](https://github.com/dockstore/dockstore/assets/15690332/a4c8d31a-8576-47b7-b56e-0ad2ebbdbd3f)

**Desktop (please complete the following information):**

* OS: Windows 11
* Browser: Chrome
* Version: Version 121.0.6167.185 (Official Build) (64-bit)

**Additional context**

* UI version: [e.g. 2.5.0]
* Webservice version: [e.g. 1.8.0]
* host location: [e.g. staging.dockstore.org]

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2513)
┆Attachments: <a href="https://api.atlassian.com/ex/jira/9ff674c1-1cd9-4ee6-9138-6e2cdc7b3740/rest/api/2/attachment/content/11139">image-20240229-181551.png</a>
┆Fix Versions: Dockstore 1.15.x
┆Issue Number: DOCK-2513
┆Sprint: 132 - Elutherios
┆Issue Type: Story

**Comment by denis-yuen** [comment]
If I understand correctly, I think this is a side-effect of https://github.com/dockstore/dockstore-ui2/pull/1847/files 
Specifically, https://github.com/dockstore/dockstore-ui2/pull/1847/files#diff-66534e02e69ab397630825a0c292b82ba81f7d4da3d46a77389e2f8303b162e3R254-R255 probably need to be further boosted. 

The workflows with the term "TheiaProk" in their `Path` are in the search results but lower ranked currently, I'd guess because "TheiaProk" only shows up once in the `Path` but many more times in the `Description` or `Source Files` of other workflows.  

![Screenshot from 2024-02-21 10-43-05](https://github.com/dockstore/dockstore/assets/1730679/f6873cdb-c2e1-463f-8d15-73ffedea74d6)
