### ISSUE TITLE
nf-core github app - not installed on specific workflows - e.g. reportho and demo

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#5917]
**Describe the bug**
From GA4GH call, although we’ve been getting some nf-core updates up to roughly May

https://dockstore.org/organizations/nfcore/collections/pipelines

It seemed from bentsherman  that some nf-core workflows were out-of-date. 

Investigate whether this means the app hasn’t been installed on certain workflows, are we missing updates, has the app broken over time, etc.

**Expected behavior**
Dockstore should have the same number of workflows as nf-core and with the same dates

**Additional context**

[Domain] - https://dockstore.org

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.15.2)

* 1.15.2

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.12.2)

* 2.12.2

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.15.0)

* 1.15.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2535)
┆Fix Versions: Dockstore 1.16.x
┆Issue Number: DOCK-2535
┆Sprint: 141 - Narbo
┆Issue Type: Story

**Comment by bentsherman** [comment]
On closer inspection, it looks like the pipelines are up to date in Dockstore. I think what threw me off was that the "Engine Versions" reported by Dockstore are not consistent. For example, looking at rnaseq, Dockstore says "!>=22.10.1" but the latest version of rnaseq is "!>=23.04.0" :

https://github.com/nf-core/rnaseq/blob/b89fac32650aacc86fcda9ee77e00612a1d77066/nextflow.config#L324

Also, nf-core/fetchngs is missing which surprised me. Maybe it was created after you implemented the initial sync. So it might be worthwhile to review the https://nf-co.re/pipelines page for any prominent pipelines that are missing. That page can also tell you which ones are deprecated.

One more note about the Versions tab... going forward, I think it will be more useful to display the minimum Nextflow version instead of DSL1/2 for the "Language Versions" column. The DSL2 label will become increasingly useless because we add new features with every stable release, so you really need to know the minimum Nextflow version in order to run the pipeline.

**Comment by denis-yuen** [comment]
Thanks, I've confirmed these and split out two different tickets. We'll get in touch with some nf-core folks to see what is going on with the app.

**Comment by coverbeck** [comment]
I think what is happening is the facets on the search page  show engine versions for all of the workflows' versions. So while your latest version of rnaseq has `!>=23.04.0`, other versions of the workflow require different engines, and all the engine versions for all the workflow versions are displayed.

If you do [this search](https://dockstore.org/search?descriptorType=NFL&entryType=workflows&ANDSplitFilter=rnaseq%20quality%20Salmon&searchMode=files), `!>=23.04.0` is there, along with other engine versions.

But then we don't show you which workflow version requires which engine version in the UI when you get to workflow's page, so it's hard to tell. #5918 is a good idea.

**Comment by denis-yuen** [comment]
Agreed on 5918, replied on the other thread about the engine version

**Comment by denis-yuen** [comment]
Oh, I did notice a couple issues with nextflow workflows which failed builds like https://github.com/nf-core/genomeskim/tree/dev or workflows which have not been updated to dsl2 and are not compatible with newer nextflow versions, may split that out

**Comment by denis-yuen** [comment]
Closing, I think the last issue was addressed with https://ucsc-cgl.atlassian.net/browse/SEAB-5994
Will re-open or spin-off tickets if we identify follow-up issues
